import random                             #importing random input
import sys                                #import system module

computerscore=0                           #initializing the values
userscore=0
count = 0

def game():                             #creating a function        
    global count
  
    while count < 3 :                   #condition for looping
   
        user=input("enter your choice")           #taking input 
        choices={1:"rock",2:"paper",3:"scissors"}
        computer = choices[random.randint(1,3)]     #random input generated by computer
    
        global computerscore                        #displaying the score
        global userscore
   
        if user == computer:                      #tie condition
            print("Tie")
        
            count = count + 1
            game()
                       
        elif user == "rock":              
            if computer == "paper":                 #condition for lose               
                print("You lose")
                computerscore = computerscore + 1
                
           
                count = count + 1                   #incrementing the counter
                print(computerscore)
                print(userscore)
                game()
            
            
            else:
                print("You win")                   #winning condition
                userscore = userscore + 1 
                count = count + 1
                print(userscore)
                print(computerscore)
                user()
            
        elif user == "paper":                       #checking different conditions
            if computer == "scissors":
                print("You lose")
                computerscore = computerscore + 1
            
                count = count + 1                        
                print(userscore)
                print(computerscore)  
                game()
            
            else:
                print("You win")                        #checking different conditions
                userscore = userscore + 1
            
                count = count + 1
                print(userscore)
                print(computerscore)
                game()
        elif user== "scissors":                        
            if computer == "rock":
                print("You lose")
                computerscore = computerscore + 1   
            
                count = count + 1
                game()
            
            else:
                print("You win" )                           
                userscore = userscore + 1 
                count = count + 1
                print(userscore)
                print(computerscore)
                game()
           
            
        else: 
            print("It's not a valid play. Check the spelling please")
            count = count + 1
            game()
    if count == 3 :
        count = 0
        try_again()
    
def try_again():                                        
    choice=input("Do you want to continue? y/n") 
    if choice=="y":                                     
        return computerscore
        return userscore
        game()
        
    
    elif choice=="n":                                   
        print("Thank you for playing")
        quit()
    else:
        print("try again")
        try_again()
game()
